name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - feature
      - test-lint
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: 'tools/eksDistroBuildToolingOpsTools'
          # Disable package caching to avoid a double cache with setup-go.
          skip-pkg-cache: true
          args: --timeout 10m